# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - init: npm install && npm install -g sfdx-cli

vscode:
  extensions:
    - dbaeumer.vscode-eslint
    - financialforce.lana
    - redhat.vscode-xml
    - salesforce.salesforcedx-vscode
